### ISSUE TITLE
Cannot launch.

### ISSUE THREAD

**Issue by identxxy** [Linyou/taichi-ngp-renderer#1]
This is a brilliant work. But some small issues stops it from launching...

1. Annotation [here](https://github.com/Linyou/taichi-ngp-renderer/blob/main/taichi_ngp.py#L562) raises an error. 
I think you need to add `from typing import Tuple` at the beginning, and change the annotation to `->Tuple[float, int, int]`.

2. After remove the annotation, some errors still occur about the args. My launch script is the same as the one in `readme.md`, which is `python taichi_ngp.py --gui --scene lego` 
```
Traceback (most recent call last):
  File "taichi_ngp.py", line 771, in <module>
    main(args)
  File "taichi_ngp.py", line 739, in main
    if args.ckpt_path:
AttributeError: 'Namespace' object has no attribute 'ckpt_path'
```

Hope you can fix these soon :)

**Comment by Linyou** [comment]
Hi, @identxxy. Thanks report this. It was a mistake that I changed `ckpt_path ` to `model_path` and forgot to update line 739. Please `git pull` and try it again!
