### ISSUE TITLE
fps

### ISSUE THREAD

**Issue by juneleung** [Linyou/taichi-ngp-renderer#16]
Hello,

I want to ask is there any way to increase the running fps?

I only have 2fps running locally, but it seems that my cpu and gpu still have a lot of space?

Thanks

![image](https://github.com/Linyou/taichi-ngp-renderer/assets/32699460/703b7c8a-00f3-418c-beda-c34fef9fc186)

**Comment by Linyou** [comment]
Hi, I think the camera is set where there's a lot of floaters. This makes the ngp pick up a bunch of points and slows down the rendering speed. I made the camera's circle a bit smaller. You should see it run faster now, about 20+ FPS on a 3090. 

Try it out! And feel free to reopen thiw issue if there is still a problem.

**Comment by juneleung** [comment]
Hi Linyou,

Thanks for your answer and I retry the project.

It seems can run to 12fps, but I found the 3090 only use 10 of 24GB, does anyway can improve fps by using full GPU memory or multi GPU?

![image](https://github.com/Linyou/taichi-ngp-renderer/assets/32699460/d39bd891-8683-4421-a6be-7b23f2b552a7)

and I also found when I move to some place, it will crash with the illegal memory, shown as:


python taichi_ngp.py --gui --scene garden
[Taichi] version 1.6.0, llvm 15.0.1, commit f1c6fbbd, win, python 3.8.13
[Taichi] Starting on arch=cuda
Loading model from ./npy_models/garden.npy
----model loaded----
K:
[[961.    0.  648.5]
 [  0.  963.  420. ]
 [  0.    0.    1. ]]
pose:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
half size:  [16. 16. 16.]
rgb_depth:  2
cascades:  6
scale:  16.0
per_level_scales:  1.662475824356079
net_width:  64
sigma_n_input:  32
sigma_n_output:  16
rgb_n_input:  32
rgb_n_output:  3
sigma_model_size:  3072
rgb_model_size:  7168
sigma_sm_preload:  24
rgb_sm_preload:  56
----GridEncoding----
base_resolution: 16
log_scale:1.66248
feature_per_level: 2 logT: 524288
level: 16
[W 07/24/23 13:15:02.645 45532] [type_check.cpp:taichi::lang::TypeCheck::visit@166] [$3708] Field index 0 not int32, casting into int32 implicitly
File "taichi_ngp.py", line 536, in raymarching_test_kernel:
                occ = self.density_bitfield[ti.u32(idx//8)] & (1 <<
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[E 07/24/23 13:15:24.735 45532] [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *>::operator ()@92] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling stream_synchronize (cuStreamSynchronize)


Traceback (most recent call last):
  File "taichi_ngp.py", line 1110, in <module>
    main(args)
  File "taichi_ngp.py", line 1087, in main
    ngp.render_gui()
  File "taichi_ngp.py", line 1033, in render_gui
    _, _, _ = self.render(
  File "taichi_ngp.py", line 818, in render
    N_alive = self.counter[None]
  File "C:\Users\Juneleung\miniconda3\envs\VRenv\lib\site-packages\taichi\lang\util.py", line 321, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\Juneleung\miniconda3\envs\VRenv\lib\site-packages\taichi\lang\field.py", line 378, in __getitem__
    return self.host_accessors[0].getter(*padded_key)
  File "C:\Users\Juneleung\miniconda3\envs\VRenv\lib\site-packages\taichi\lang\field.py", line 405, in getter
    return read_func(key)
RuntimeError: [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *>::operator ()@92] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling stream_synchronize (cuStreamSynchronize)
[E 07/24/23 13:15:24.870 45532] [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *>::operator ()@92] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling stream_synchronize (cuStreamSynchronize)
