### ISSUE TITLE
Compared with instant-NGP

### ISSUE THREAD

**Issue by ElonKou** [Linyou/taichi-ngp-renderer#2]
Thanks for you great work! 
I have a question about that does it improved rendering speed compared with origin CUDA code?

**Comment by Linyou** [comment]
Hi @ElonKou. My implementation is still slower than the original repo [instant-ngp](https://github.com/NVlabs/instant-ngp). In the `Lego` scene, the original is 90+ fps while taichi-ngp is around 70. However, compared to the existing python implementation, taichi-ngp is still faster. Also, taichi allows you to run anywhere besides the Nvidia graphic card. For example, you can run this code on a Mac through the Vulkan backend. 

Note that there is still much room for improvement in taichi-ngp.
