### ISSUE TITLE
Successive render() calls deteriorate the generated rgb frames.

### ISSUE THREAD

**Issue by plbeaubien** [Linyou/taichi-ngp-renderer#4]
The generated buffer is only valid after the first call to the render() function, successive calls get increasingly corrupted.

ex:
  ngp = NGP_fw(...)
  ngp.render()  # <- outputs the proper .png
  ngp.render()  # <- outputs a degraded .png
  ngp.render()  # <- outputs a more degraded .png

**Comment by Linyou** [comment]
Hi, I have fixed this problem with a pr. 

Now you can call `ngp.render()` multiple times.

Also, please see the function [`render_frame` ](https://github.com/Linyou/taichi-ngp-renderer/blob/090c3106712cc9edf1706750bfa5d13467efeefa/taichi_ngp.py#L760). This function allow you to render multiple frames and print out the running time.
